<a href="https://colab.research.google.com/github/Ishra18-hub/Solar-Desalination-ML/blob/main/06_numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BROADCASTING

In [ ]:
import numpy as np

# Scalar + Array
a = np.array([1, 2, 3])
print(a + 10)

# 1D + 2D
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print(matrix + row)

# Column + Row
col = np.array([[1], [2]])
print(matrix + col)


[11 12 13]
[[11 22 33]
 [14 25 36]]
[[2 3 4]
 [6 7 8]]


In [ ]:
# FYDP

temperatures = np.array([320, 333, 345, 354, 365])
print(temperatures + 10)

# Temperature normalization
normalized = (temperatures - np.mean(temperatures)) / np.std(temperatures)
print(normalized)

[330 343 355 364 375]
[-1.48758196 -0.66114754  0.10171501  0.67386191  1.37315258]


RANDOM NUMBER CREATE

In [ ]:
# Random integers
print(np.random.randint(1, 100, 5))

# Random floats (0-1)
print(np.random.rand(5))

# Normal distribution
print(np.random.randn(5))

# Seed (reproducible)
np.random.seed(42)
print(np.random.rand(3))

[60 25 61 58 24]
[0.48383849 0.46763319 0.39321217 0.46533796 0.91140774]
[-1.799002   -0.56076322 -0.2982368  -0.8031416   0.27552466]
[0.37454012 0.95071431 0.73199394]


ML-USE

In [ ]:
# Train-test split
data = np.arange(100)
np.random.seed(42)
indices = np.random.permutation(100)
train_idx = indices[:80]
test_idx = indices[80:]
print(f"Train: {len(train_idx)}, Test: {len(test_idx)}")

Train: 80, Test: 20


Linear Algebra ( Need for Linear Regression)

In [ ]:
A = np.array([[1, 2], [3, 4]])

# Determinant
print(np.linalg.det(A))

# Inverse
print(np.linalg.inv(A))

# Eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

# Matrix multiplication (Dot Product)
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[19 22]
 [43 50]]


Normal Equation (Linear Regression)

In [ ]:
# θ = (X^T X)^-1 X^T y
X = np.array([[1, 320], [1, 333], [1, 345], [1, 354], [1, 365]])
y = np.array([0.40, 0.58, 0.75, 1.00, 1.20])

theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(f"Theta: {theta}")
# [intercept, slope]

Theta: [-5.41140963  0.0180472 ]


In [ ]:
# FYDP DATASETS
# NumPy Advanced Practice

import numpy as np

# Broadcasting
temperatures = np.array([320, 333, 345, 354, 365])
normalized = (temperatures - np.mean(temperatures)) / np.std(temperatures)
print(f"Normalized: {normalized}")

# Random for ML
np.random.seed(42)
shuffled = np.random.permutation(temperatures)
print(f"Shuffled: {shuffled}")

# Linear Algebra
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(f"Theta: {theta}")

# Boolean Masking
high_temp = temperatures[temperatures > 340]
print(f"High temps: {high_temp}")

# np.where()
labels = np.where(temperatures > 340, "High", "Low")
print(f"Labels: {labels}")

Normalized: [-1.48758196 -0.66114754  0.10171501  0.67386191  1.37315258]
Shuffled: [333 365 345 320 354]
Theta: [-1.77635684e-15  1.00000000e+00]
High temps: [345 354 365]
Labels: ['Low' 'Low' 'High' 'High' 'High']
