In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

print(np.__version__)

2.1.3


0-D ARRAYS

In [ ]:
import numpy as np

arr = np.array(40)

print(arr)

40


1-D ARRAYS

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D ARRAYS

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Create a 3-D array with two 2-D arrays

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


EXERCISE 1

In [ ]:
# 1D Array
temperatures = np.array([320, 333, 345, 354, 365])
print(temperatures)

# 2D Array
data = np.array([[320, 0.45], [333, 0.65], [345, 0.82]])
print(data)

# Zeros, Ones, Range
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

[320 333 345 354 365]
[[320.     0.45]
 [333.     0.65]
 [345.     0.82]]


Verifying dimensions

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


Indexing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


Access 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


Access 3-D Arrays

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('3rd element of the second array of the first array: ', arr[0, 1, 2])

3rd element of the second array of the first array:  6


Negative Indexing

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])  # negative slicing
print(arr[1:5:2])  # using the step value [start:end:step]
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


Slicing 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


EXERCISE 2

In [ ]:
# FYDP DATA
temperatures = np.array([320, 333, 345, 354, 365])
evaporation = np.array([0.45, 0.65, 0.82, 1.00, 1.28])

# Indexing
print(temperatures[0])
print(temperatures[-1])
print(temperatures[2])

# Slicing
print(temperatures[1:4])
print(temperatures[:3])
print(temperatures[::2])


320
365
345
[333 345 354]
[320 333 345]
[320 345 365]


2D Array Indexing

In [ ]:
# FYDP Table (Temperature, Evaporation, Yield)
data = np.array([
    [320, 0.45, 0.40],
    [333, 0.65, 0.58],
    [345, 0.82, 0.75],
    [354, 1.00, 1.00],
    [365, 1.28, 1.20]
])

# Row, Column
print(data[0])        # First row
print(data[:, 0])     # First column (Temperature)
print(data[1, 2])     # Row 1, Column 2 = 0.58
print(data[2:4, :])   # Rows 2-3

[320.     0.45   0.4 ]
[320. 333. 345. 354. 365.]
0.58
[[345.     0.82   0.75]
 [354.     1.     1.  ]]


Array Attributes

In [ ]:
print(data.shape)     # (Rows × Columns) or (5, 3)
print(data.ndim)      # 2 (Number of Dimensions)
print(data.size)      # how many elements?(5 Rows × 3 Columns = 15 Elements)
print(data.dtype)     # (Data Type) it's float64

(5, 3)
2
15
float64


Array Math

Element wise operation

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]


Statistical Operations

In [ ]:
temperatures = np.array([320, 333, 345, 354, 365])

print(f"Mean: {np.mean(temperatures)}")
print(f"Median: {np.median(temperatures)}")
print(f"Std: {np.std(temperatures)}")         # Standard Deviation
print(f"Max: {np.max(temperatures)}")
print(f"Min: {np.min(temperatures)}")
print(f"Sum: {np.sum(temperatures)}")

Mean: 343.4
Median: 345.0
Std: 15.730225681788548
Max: 365
Min: 320
Sum: 1717


Dot Product (For Linear Regression)

In [ ]:
# FYDP Efficiency Calculation
# η = m * hfg / (I * A * t)

m = np.array([0.001, 0.002, 0.003])      # mass flow rate
hfg = 2260000                              # latent heat
I = np.array([1000, 1000, 1000])          # irradiance
A = 1                                      # area
t = 3600                                   # time

efficiency = (m * hfg) / (I * A * t)
print(f"Efficiency: {efficiency}")

Efficiency: [0.00062778 0.00125556 0.00188333]


Matrix Operations

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))       # Matrix multiplication
print(A.T)                # Transpose
print(np.linalg.inv(A))   # Inverse

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Exercise 3

In [ ]:
# FYDP data

data = np.array([
    [320, 0.45, 0.40, 5],
    [333, 0.65, 0.58, 8],
    [345, 0.82, 0.75, 10],
    [354, 1.00, 1.00, 12],
    [365, 1.28, 1.20, 15]
])
# Columns: Temperature, Evaporation, Yield, Air_Flow

# Extract Temperature column
temp = data[:, 0]
print(f"Temperatures: {temp}")

# Calculate mean temperature
print(f"Mean Temperature: {np.mean(temp):.2f} K")

# Extract Yield column
yield_ = data[:, 2]
print(f"Yields: {yield_}")

# Find max yield
max_yield = np.max(yield_)
max_index = np.argmax(yield_)
print(f"Max Yield: {max_yield} at Temperature {temp[max_index]} K")

# Filter high temperature observations
high_temp = data[data[:, 0] > 340]
print(f"High temperature data:\n{high_temp}")

Temperatures: [320. 333. 345. 354. 365.]
Mean Temperature: 343.40 K
Yields: [0.4  0.58 0.75 1.   1.2 ]
Max Yield: 1.2 at Temperature 365.0 K
High temperature data:
[[345.     0.82   0.75  10.  ]
 [354.     1.     1.    12.  ]
 [365.     1.28   1.2   15.  ]]
